
@base_url = http://localhost:3000/api
get {{base_url}}/persons

### Delete test for user 4
delete {{base_url}}/persons/175881300949215

### PUT test for user 1

put {{base_url}}/persons/1
Content-Type: application/json

{
    "name": "hernan ruscica",
    "number": "1132924558"
}

### post test
post {{base_url}}/persons
Content-Type: application/json

{
    "name": "Ada salvatierra",
    "number": "145823"
}

### Testing no routes
get {{base_url}}/noroute